sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec web --env 'RAILS_ENV=test' rails db:create
  - docker-compose exec web --env 'RAILS_ENV=test' rails db:migrate
  - docker-compose exec web --env 'RAILS_ENV=test' rails test
