sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec web rails db:create
  - docker-compose exec web rails db:migrate
  - docker-compose exec web rails test
